### PR TITLE
Fix switch accessibility

### LINKED ISSUE #5699: Mantine Switch should follow accessibility best practices
Current Switch component fails accessibility checks for using an empty label to land user clicks on a checkbox. If user also uses the label prop a second label is created with the same `for` target which is also not allowed. 

Consider reworking the component to behave more like the [W3C APG example ](https://www.w3.org/WAI/ARIA/apg/patterns/switch/examples/switch/)

### PR DESCRIPTION
**Pull request by rilrom**
Fixes #5699.

Things to note:

- Due to the implementation of `role="switch"`, some tests needed to be adjusted.
- Screen readers no longer read out the `onLabel` and `offLabel` values, however I consider this to be appropriate as the `label` or `aria-label` should be used to provide enough context that these values are not needed.
- Screen reader testing was conducted across macOS VoiceOver and Windows NVDA.
- Open to suggestions on types for `bodyElement` and `labelElement`.

### CODE REVIEW

File: packages/@mantine/core/src/components/Switch/Switch.tsx [hunk 1]
```diff
@@ -208,12 +210,12 @@ export const Switch = factory<SwitchFactory>((_props, ref) => {
...
         ref={ref}
         type="checkbox"
+        role="switch"
         {...getStyles('input')}
       />
 
       <Box
-        component="label"
-        htmlFor={uuid}
+        aria-hidden="true"
```
Comment (ocshawn) [inline packages/@mantine/core/src/components/Switch/Switch.tsx:218]: i would argue that the aria-hidden is not needed, as this will not be read if empty, but this will prevent any text from be read if onLabel  or offLabel are used

**Review by ocshawn — CHANGES_REQUESTED** [review]
please explain reasoning for aria- hidden, otherwise everything looks great

File: packages/@mantine/core/src/components/InlineInput/InlineInput.tsx [hunk 2]
```diff
@@ -36,6 +36,8 @@ export interface InlineInputProps
   error: React.ReactNode;
   size: MantineSize | (string & {}) | undefined;
   labelPosition?: 'left' | 'right';
+  bodyElement?: any;
+  labelElement?: any;
```
Comment (ocshawn) [inline packages/@mantine/core/src/components/InlineInput/InlineInput.tsx:40]:
```suggestion
  bodyElement?: string;
  labelElement?: string;
```
should also be changed from any

**Review by ocshawn — CHANGES_REQUESTED** [review]

File: packages/@mantine/core/src/components/Switch/Switch.tsx (hunk 1 above)
Comment (ocshawn) [reply packages/@mantine/core/src/components/Switch/Switch.tsx:218]: after re reading the accessibility documentation found at https://www.w3.org/WAI/ARIA/apg/patterns/switch/examples/switch-checkbox/ i retract my question

**Review by ocshawn — APPROVED** [review]

**Comment by rtivital** [comment]
Thanks!
