### PR TITLE
[@mantine/core] Combobox: Fix #5427

### LINKED ISSUE #5427: Combobox onClose does not work
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.3.2

### What package has an issue?

@mantine/core

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

Firefox

### Describe the bug

I took the first code example from the [Combobox examples page](https://mantine.dev/combobox/?e=BasicSelect) called "Basic select". Added `onClose={() => alert('onClose')}` to Combobox component. The event does not trigger when I close dropdown. `onOpen` works just fine though.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/infallible-leakey-5w99kk

### Possible fix

_No response_

### Self-service

- [ ] I would be willing to implement a fix for this issue

### PR DESCRIPTION
**Pull request by ID-JA**
Fixes #5427

### CODE REVIEW

File: packages/@mantine/core/src/components/Combobox/Combobox.tsx [hunk 1]
```diff
@@ -159,7 +160,7 @@ export function Combobox(_props: ComboboxProps) {
       <Popover
         opened={store.dropdownOpened}
         {...others}
-        onClose={store.closeDropdown}
+        onClose={onClose || store.closeDropdown}
```
Comment (rtivital) [inline packages/@mantine/core/src/components/Combobox/Combobox.tsx:163]: I suppose that it would be better to call both functions:

`() => {onClose?.(); store.closeDropdown()}`

Comment (ID-JA) [reply packages/@mantine/core/src/components/Combobox/Combobox.tsx]: I agree it's a good idea to call both functions. I've updated it to trigger both close handlers

**Comment by rtivital** [comment]
Thanks!
