### PR TITLE
[@mantine/form] Call `form.watch` subscribers on `form.initialize`

### LINKED ISSUE #6638: form.watch does not trigger when form.initialize is called
### Dependencies check up

- [X] I have verified that I use latest version of all @mantine/* packages

### What version of @mantine/* packages do you have in package.json?

7.12.0

### What package has an issue?

@mantine/form

### What framework do you use?

Vite

### In which browsers you can reproduce the issue?

All

### Describe the bug

When using and uncontrolled form and form.watch will not trigger when form.initialize is called. In this case, the value will correctly update but the change will not be transmitted to the form.watch subscribers.

The expected behavior is the subscribers being called every time the value changes, including by the form initialization using form.initialize.

In the provided codesandbox it is shown an example of a staled value (empty) being rendered because of this problem.

### If possible, include a link to a codesandbox with a minimal reproduction

https://codesandbox.io/p/sandbox/elegant-saha-h5cs6f

### Possible fix

_No response_

### Self-service

- [X] I would be willing to implement a fix for this issue

### PR DESCRIPTION
**Pull request by raulfpl**
Fixes #6638

This PR adds tests covering the problem of `form.watch` subscribers not being called when the value changes because of `form.initialize()` as described in #6638 and fixes it.

The way it fixes it is by notifying the subscribers the same way `setValues` does it.

Let me know if this is not the right way to fix this.

### CODE REVIEW

File: packages/@mantine/form/src/use-form.ts [hunk 1]
```diff
@@ -62,8 +62,22 @@ export function useForm<
   }, []);
 
   const initialize: Initialize<Values> = useCallback((values) => {
+    const previousValues = $values.refValues.current;
     $values.initialize(values, () => mode === 'uncontrolled' && setFormKey((key) => key + 1));
-  }, []);
+    clearInputErrorOnChange && $errors.clearErrors();
+    mode === 'uncontrolled' && setFormKey((key) => key + 1);
+
+    Object.keys($watch.subscribers.current).forEach((path) => {
```
Comment (rtivital) [inline packages/@mantine/form/src/use-form.ts:70]: This logic must not be duplicated, it is already present in setValues handler.

**Review by rtivital — CHANGES_REQUESTED** [review]

**Comment by rtivital** [comment]
Thanks!
